fix: disable HA bluetooth integration
Bluetooth scanner errors due to bluez backend not properly initialized.
Disabled bluetooth integration in HA config until bluetooth devices needed.

Error: hci0 Failed to force stop scanner: 'NoneType' object has no attribute 'send'
Signed-off-by: Marcin Skalski <skalskimarcin33@gmail.com>